// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHh7WljKpvU5onBeOvAQxpuOFb1eQAr8',
    appId: '1:29691384055:web:30f5abd093dd8ca091c3f2',
    messagingSenderId: '29691384055',
    projectId: 'mynotes-prokopev',
    authDomain: 'mynotes-prokopev.firebaseapp.com',
    storageBucket: 'mynotes-prokopev.appspot.com',
    measurementId: 'G-XH23FMY8XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5dWPbnnpO1jF6lBdZKjaSMd4LKOn0-_s',
    appId: '1:29691384055:android:fedf5f8a0274135a91c3f2',
    messagingSenderId: '29691384055',
    projectId: 'mynotes-prokopev',
    storageBucket: 'mynotes-prokopev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg3kE_pMuB_MExd9a93qkN3iDZHbC2rO4',
    appId: '1:29691384055:ios:8287657f98c8c23691c3f2',
    messagingSenderId: '29691384055',
    projectId: 'mynotes-prokopev',
    storageBucket: 'mynotes-prokopev.appspot.com',
    iosClientId: '29691384055-b73f9cqcp9bn5ibghuekau9cb2vma9uv.apps.googleusercontent.com',
    iosBundleId: 'com.makingapplications.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg3kE_pMuB_MExd9a93qkN3iDZHbC2rO4',
    appId: '1:29691384055:ios:250c45a02b92a17691c3f2',
    messagingSenderId: '29691384055',
    projectId: 'mynotes-prokopev',
    storageBucket: 'mynotes-prokopev.appspot.com',
    iosClientId: '29691384055-gl1bos1jrdutl0laeslqj179pbbj1spq.apps.googleusercontent.com',
    iosBundleId: 'com.makingapplications.mynotes.RunnerTests',
  );
}
